version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gendev24
    ports:
      - "5434:5432"
    volumes:
      - ./server/prisma/dump.sql:/docker-entrypoint-initdb.d/dump.sql