export const getProviderImage = (providerId: number) => {
    const providerImages: Record<number, string> = {
        2: "src/assets/streamingProviders/2.png",
        3: "src/assets/streamingProviders/3.png",
        4: "src/assets/streamingProviders/4.png",
        5: "src/assets/streamingProviders/5.png",
        10: "src/assets/streamingProviders/10.png",
        13: "src/assets/streamingProviders/13.png",
        14: "src/assets/streamingProviders/14.png",
        15: "src/assets/streamingProviders/15.png",
        16: "src/assets/streamingProviders/16.png",
        17: "src/assets/streamingProviders/17.png",
        18: "src/assets/streamingProviders/18.png",
        19: "src/assets/streamingProviders/19.png",
        20: "src/assets/streamingProviders/20.png",
        35: "src/assets/streamingProviders/35.png",
        36: "src/assets/streamingProviders/36.png",
        37: "src/assets/streamingProviders/37.png",
        38: "src/assets/streamingProviders/38.png",
        39: "src/assets/streamingProviders/39.png",
        40: "src/assets/streamingProviders/40.png",
        41: "src/assets/streamingProviders/41.png",
        42: "src/assets/streamingProviders/42.png",
        43: "src/assets/streamingProviders/43.png",
        44: "src/assets/streamingProviders/44.png",
        45: "src/assets/streamingProviders/45.png",
        46: "src/assets/streamingProviders/46.png",
        47: "src/assets/streamingProviders/47.png",
        48: "src/assets/streamingProviders/48.png",
        49: "src/assets/streamingProviders/49.png",
        50: "src/assets/streamingProviders/50.png",
        51: "src/assets/streamingProviders/51.png",
        52: "src/assets/streamingProviders/52.png",
        53: "src/assets/streamingProviders/53.png",
        54: "src/assets/streamingProviders/54.png",
        55: "src/assets/streamingProviders/54.png",
        56: "src/assets/streamingProviders/15.png",
        57: "src/assets/streamingProviders/57.png",
        58: "src/assets/streamingProviders/58.png",
    };
    return providerImages[providerId] || "../assets/streamingProviders/undefined.png"
};